name: CI

on: [push, pull_request]

env:
  NODE_VERSION: 14.x

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2
      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
        env:
          CI: true

  lint-code:
    runs-on: ubuntu-latest
    needs: [ install ]

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Lint
        run: yarn lint
        env:
          CI: true

  lint-commit-msg:
    runs-on: ubuntu-latest
    needs: [ install ]

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Lint commit message
        run: yarn run commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD
        env:
          CI: true

  test:
    runs-on: ubuntu-latest
    needs: [ install ]

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Test
        run: yarn test
        env:
          CI: true

  build:
    runs-on: ubuntu-latest
    needs: [ install ]

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Build
        run: yarn build
        env:
          CI: true
