name: Release dev

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 14
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Test
        run: npm test
        env:
          CI: true

      - name: Publish
        run: npm publish -w packages --tag dev
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
